### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/DynamicTrees-PHC#1]
This is the main list of progress for Pam's Harvestcraft compatibility.

- [x] Fruit Trees working
- [x] Alter Pam's Harvestcraft codebase to accomodate Dynamic Trees
- [x] Make fruit right click on fruit block drop entire block(grows back)
- [x] Disable harvestcraft worldgen
- [x] Create pull request for Pam's Harvestcraft
- [x] Dirt bucket exchange recipes (fruit -> seed, sapling <-> seed)
- [x] Make JoCodes list for select trees
- [x] Make pixel art textures for seeds
- [x] Bark/Sap product trees(Paper, Maple, Cinnamon)
- [x] Make bark harvestable(Paper, Cinnamon)
- [x] Banana palm
- [x] Spile and bucket harvest for Maple Sap

**Comment by darthvader45** [comment]
Looks cool, I especially like having those exchange recipes in case I need the vanilla trees.

**Comment by DogMakeAMove** [comment]
Excited as hell for this one! 
Can't wait to be able to use this thanks for your work

**Comment by VinterNacht** [comment]
I count the days my friend, I count the days.

**Comment by nephatrine** [comment]
In addition to "banana palm", coconuts and dates grow on palm trees as well. The Dynamic Trees BOP addon has really nice palms so it'd be cool to have that style of tree for some of the ones in this mod as well. Is it totally out of the realm of possibility to be able to specify the wood/leaf type and tree style in a config for each tree? That'd maybe allow people to add their own cross-mod compat so for instance cherry trees could have cherry leaves/wood and palm-type trees can have palm wood, etc. I know that's going above and beyond what PHC does to begin with, but with all the nice trees it's a shame the PHC ones are still so generic/vanilla.

**Comment by VinterNacht** [comment]
@ferreusveritas so much what @nephatrine said about wood types... so much.  Any way to have it check to see if BOP is installed to determine the type of wood used? Just to start?

**Comment by erebus42** [comment]
Awesome mod.  You could consider adding support for Pam's Spooky Tree and Pam's Redbud Trees. :)

**Comment by Btmy520** [comment]
I don’t know if the dynamic tree worldgen is turned on, but I really don’t see pam’s trees

**Comment by VinterNacht** [comment]
> I don’t know if the dynamic tree worldgen is turned on, but I really don’t see pam’s trees

I noticed this myself on recent builds.

**Comment by ghost** [comment]
TODO List in complete
